# Generated by Django 6.1 on 2026-09-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('start_year', models.IntegerField()),
                ('end_year', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('color_theme', models.CharField(choices=[('amber', 'Amber'), ('cyan', 'Cyan'), ('purple', 'Purple'), ('rose', 'Rose')], default='amber', max_length=10)),
            ],
        ),
    ]
