# Generated by Django 6.1 on 2026-09-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_experience_category'),
        ('main', '0005_project_starred_by'),
    ]

    operations = [
    ]
